version: '2'
services:
    zlotadmin2-postgresql:
        image: postgres:9.6.5
        # volumes:
        #     - ~/volumes/jhipster/zlotadmin2/postgresql/:/var/lib/postgresql/data/
        environment:
            - POSTGRES_USER=zlotadmin2
            - POSTGRES_PASSWORD=
        ports:
            - 5432:5432
